Ajuste Performance fase 2 VIS
philips-emr/vis pull request #126
Opened 2023-05-02 19:31 UTC by netto-franco91

2023-05-04 15:38 UTC, vandersonpaim requested changes

2023-05-04 15:38 UTC, vandersonpaim commented on lib/timeline/component/Group.js
> +  });
por favor verificar este return dentro de um fastdom.measure(function () {

2023-05-04 19:23 UTC, vandersonpaim requested changes

2023-05-04 19:23 UTC, vandersonpaim commented on lib/timeline/component/timeline-chart/DrawBackground.js
> +        const background = DOMutil.getDOMElement('div', _this.DOMelements.backgrounds, _this.dom.lineContainer);
acredito que um measure seguido de mutate não seja necessario o measure , somente o mutate .

mas teria de verificar ali se a linha :
const background = DOMutil.getDOMElement('div', _this.DOMelements.backgrounds, _this.dom.lineContainer);
deveria estar no measure .

2023-05-04 19:38 UTC, vandersonpaim requested changes

2023-05-04 19:38 UTC, vandersonpaim commented on lib/timeline/component/item/RangeItem.js
> +    fastdom.mutate(function () {
acredito que um measure seguido de mutate não seja necessario o measure , somente o mutate .

2023-05-04 19:38 UTC, vandersonpaim commented on lib/timeline/component/TimeAxis.js
> +  });
aqui também o mutante esta  fechado antes do return e o li.className esta fora do mutante.

2023-05-04 19:38 UTC, vandersonpaim commented on lib/timeline/component/TimeAxis.js
> +  });
acredito que um measure seguido de mutate não seja necessario o measure , somente o mutate .

2023-05-04 19:38 UTC, vandersonpaim commented on lib/timeline/component/DataAxis.js
> +          }
acredito que seja melhor usar o .style.setProperty( também

2023-05-08 13:14 UTC, vandersonpaim requested changes

2023-05-08 13:51 UTC, vandersonpaim requested changes

2023-05-08 13:51 UTC, vandersonpaim commented on lib/timeline/Core.js
>    dom.backgroundHorizontal.style.height = centerContainerHeight;
por favor adicionar .style.setProperty( quando o dom estiver recebendo alterações no style.

2023-05-08 14:52 UTC, masborchardt approved these changes

2023-05-08 14:55 UTC, masborchardt commented
Verifiquei nos exemplos documentado na lib FASTDOM que o mutate pode ser chamado tanto dentro quanto fora de um measure, portanto, não temos um padrão estabelicido.

2023-05-09 13:59 UTC, vandersonpaim approved these changes

2023-05-09 13:59 UTC, merged