Sync hovered and selected rows in the timeline charts mode [SO-2366765]
philips-emr/vis pull request #20
Opened 2021-03-17 20:39 UTC by netto-franco91

2021-03-25 13:04 UTC, hsteffens requested changes

2021-03-25 13:04 UTC, hsteffens commented on lib/timeline/component/timeline-chart/TimelineChartDataAxis.js
> +      width: (document.querySelector('.data-region.data-container-with-timeline')) ? parseInt(document.querySelector('.data-region.data-container-with-timeline').offsetWidth / 26) + 'px' : '0px',
Please not execute twice document.querySelector('.data-region.data-container-with-timeline')

2021-03-25 13:04 UTC, hsteffens commented on lib/timeline/component/DataAxis.js
> +    width: (document.querySelector('.data-region.data-container-with-timeline')) ? parseInt(document.querySelector('.data-region.data-container-with-timeline').offsetWidth / 26) + 'px' : '0px',
Please not execute twice document.querySelector('.data-region.data-container-with-timeline')

2021-04-08 00:23 UTC, rubiabornhofen approved these changes

2021-04-08 00:24 UTC, merged